# Generated by Django 6.0.7 on 2026-10-09 11:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CargaDados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_arquivo', models.CharField(max_length=255)),
                ('checksum_sha256', models.CharField(max_length=64, unique=True)),
                ('fonte', models.CharField(default='desconhecida', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('running', 'Em execução'), ('completed', 'Concluída'), ('failed', 'Falhou')], default='pending', max_length=20)),
                ('total_registros', models.PositiveBigIntegerField(default=0)),
                ('mensagem_erro', models.TextField(blank=True)),
                ('iniciado_em', models.DateTimeField(blank=True, null=True)),
                ('concluido_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'carga de dados',
                'verbose_name_plural': 'cargas de dados',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Comarca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nome', models.CharField(max_length=150)),
                ('uf', models.CharField(default='BA', max_length=2)),
                ('ativa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'comarca',
                'verbose_name_plural': 'comarcas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_ibge', models.CharField(max_length=7, unique=True)),
                ('nome', models.CharField(max_length=150)),
                ('uf', models.CharField(default='BA', max_length=2)),
                ('comarca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='municipios', to='dados.comarca')),
            ],
            options={
                'verbose_name': 'município',
                'verbose_name_plural': 'municípios',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='DemandaJudicial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.DateField(help_text='Data representativa do período, normalmente o primeiro dia do mês.')),
                ('classe_processual', models.CharField(blank=True, max_length=255)),
                ('assunto_processual', models.CharField(blank=True, max_length=255)),
                ('total_processos', models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('identificador_registro', models.CharField(help_text='Hash determinístico para permitir reprocessamento sem duplicidade.', max_length=64, unique=True)),
                ('dados_originais', models.JSONField(blank=True, default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('carga', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demandas', to='dados.cargadados')),
                ('comarca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='demandas', to='dados.comarca')),
                ('municipio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='demandas', to='dados.municipio')),
            ],
            options={
                'verbose_name': 'demanda judicial',
                'verbose_name_plural': 'demandas judiciais',
                'ordering': ['-periodo', 'comarca__nome', 'municipio__nome'],
                'indexes': [models.Index(fields=['periodo'], name='dados_deman_periodo_410bb9_idx'), models.Index(fields=['comarca', 'periodo'], name='dados_deman_comarca_4639d5_idx'), models.Index(fields=['municipio', 'periodo'], name='dados_deman_municip_049150_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('total_processos__gte', 0)), name='demanda_total_processos_nao_negativo')],
            },
        ),
    ]
