# Generated by Django 6.0.7 on 2026-10-09 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatajudRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.PositiveSmallIntegerField()),
                ('grau', models.CharField(max_length=2)),
                ('processo', models.CharField(db_index=True, max_length=25)),
                ('id_municipio', models.CharField(max_length=4)),
                ('municipio', models.CharField(max_length=27)),
                ('codigo_classe', models.TextField(help_text='Lista de códigos serializada no arquivo, por exemplo: [198,460].')),
                ('nome_classe', models.CharField(max_length=310)),
                ('codigo_assunto', models.TextField(help_text='Lista de códigos serializada no arquivo.')),
                ('nome_assunto', models.TextField(blank=True)),
                ('codigo_orgao', models.CharField(max_length=5)),
                ('nome_orgao', models.CharField(max_length=155)),
                ('carga', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_datajud', to='dados.cargadados')),
            ],
            options={
                'verbose_name': 'registro bruto do Datajud',
                'verbose_name_plural': 'registros brutos do Datajud',
                'db_table': 'datajud_registros',
                'ordering': ['-ano', 'processo'],
                'indexes': [models.Index(fields=['ano', 'grau'], name='datajud_reg_ano_2a1dbf_idx'), models.Index(fields=['id_municipio', 'ano'], name='datajud_reg_id_muni_dcaa00_idx'), models.Index(fields=['codigo_orgao', 'ano'], name='datajud_reg_codigo__a12b2e_idx')],
            },
        ),
    ]
