# Generated by Django 6.0.7 on 2026-10-09 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dados', '0002_datajudregistro'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargaAPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fonte', models.CharField(choices=[('datajud', 'Datajud/CNJ'), ('ibge', 'IBGE')], max_length=20)),
                ('identificador_origem', models.CharField(help_text='Nome do arquivo, endpoint ou identificador da coleta.', max_length=500)),
                ('endpoint', models.URLField(blank=True)),
                ('checksum_sha256', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('running', 'Em execução'), ('completed', 'Concluída'), ('failed', 'Falhou')], default='pending', max_length=20)),
                ('total_registros', models.PositiveBigIntegerField(default=0)),
                ('mensagem_erro', models.TextField(blank=True)),
                ('iniciado_em', models.DateTimeField(blank=True, null=True)),
                ('concluido_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'carga de API',
                'verbose_name_plural': 'cargas de API',
                'db_table': 'cargas_api',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='IBGEIndicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_municipio', models.CharField(db_index=True, max_length=7)),
                ('municipio', models.CharField(max_length=150)),
                ('uf', models.CharField(default='BA', max_length=2)),
                ('ano_referencia', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('indicador', models.CharField(max_length=255)),
                ('valor_numerico', models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True)),
                ('valor_textual', models.TextField(blank=True)),
                ('unidade', models.CharField(blank=True, max_length=100)),
                ('endpoint', models.URLField(blank=True)),
                ('identificador_registro', models.CharField(max_length=64, unique=True)),
                ('dados_originais', models.JSONField(blank=True, default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'indicador do IBGE',
                'verbose_name_plural': 'indicadores do IBGE',
                'db_table': 'ibge_indicadores',
                'ordering': ['-ano_referencia', 'municipio', 'indicador'],
            },
        ),
        migrations.RemoveField(
            model_name='municipio',
            name='comarca',
        ),
        migrations.RemoveIndex(
            model_name='demandajudicial',
            name='dados_deman_periodo_410bb9_idx',
        ),
        migrations.RemoveIndex(
            model_name='demandajudicial',
            name='dados_deman_comarca_4639d5_idx',
        ),
        migrations.RemoveIndex(
            model_name='demandajudicial',
            name='dados_deman_municip_049150_idx',
        ),
        migrations.RemoveConstraint(
            model_name='demandajudicial',
            name='demanda_total_processos_nao_negativo',
        ),
        migrations.AlterModelOptions(
            name='datajudregistro',
            options={'ordering': ['-ano', 'processo'], 'verbose_name': 'registro do Datajud', 'verbose_name_plural': 'registros do Datajud'},
        ),
        migrations.AlterField(
            model_name='datajudregistro',
            name='codigo_classe',
            field=models.TextField(help_text='Lista de códigos serializada, por exemplo: [198,460].'),
        ),
        migrations.AddIndex(
            model_name='cargaapi',
            index=models.Index(fields=['fonte', 'status'], name='cargas_api_fonte_51586a_idx'),
        ),
        migrations.AlterField(
            model_name='datajudregistro',
            name='carga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_datajud', to='dados.cargaapi'),
        ),
        migrations.AddField(
            model_name='ibgeindicador',
            name='carga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='indicadores_ibge', to='dados.cargaapi'),
        ),
        migrations.RemoveField(
            model_name='demandajudicial',
            name='carga',
        ),
        migrations.RemoveField(
            model_name='demandajudicial',
            name='comarca',
        ),
        migrations.RemoveField(
            model_name='demandajudicial',
            name='municipio',
        ),
        migrations.AddIndex(
            model_name='ibgeindicador',
            index=models.Index(fields=['codigo_municipio', 'ano_referencia'], name='ibge_indica_codigo__dc17ac_idx'),
        ),
        migrations.AddIndex(
            model_name='ibgeindicador',
            index=models.Index(fields=['indicador', 'ano_referencia'], name='ibge_indica_indicad_1254d3_idx'),
        ),
        migrations.AddIndex(
            model_name='ibgeindicador',
            index=models.Index(fields=['uf', 'ano_referencia'], name='ibge_indica_uf_b38960_idx'),
        ),
        migrations.DeleteModel(
            name='CargaDados',
        ),
        migrations.DeleteModel(
            name='Comarca',
        ),
        migrations.DeleteModel(
            name='DemandaJudicial',
        ),
        migrations.DeleteModel(
            name='Municipio',
        ),
    ]
