# Generated by Django 6.0.7 on 2026-10-09 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dados', '0003_cargaapi_ibgeindicador_remove_municipio_comarca_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='cargaapi',
            name='cargas_api_fonte_51586a_idx',
        ),
        migrations.RemoveField(
            model_name='datajudregistro',
            name='carga',
        ),
        migrations.RemoveIndex(
            model_name='ibgeindicador',
            name='ibge_indica_codigo__dc17ac_idx',
        ),
        migrations.RemoveIndex(
            model_name='ibgeindicador',
            name='ibge_indica_indicad_1254d3_idx',
        ),
        migrations.RemoveIndex(
            model_name='ibgeindicador',
            name='ibge_indica_uf_b38960_idx',
        ),
        migrations.RemoveField(
            model_name='ibgeindicador',
            name='carga',
        ),
        migrations.DeleteModel(
            name='CargaAPI',
        ),
        migrations.DeleteModel(
            name='IBGEIndicador',
        ),
    ]
